config/routes.rb
Code::Application.routes.draw do

    root :to => 'data_maps#index'

    match 'help' => 'info#help'
    match 'faq' => 'info#faq'
    match 'my_data_maps' => 'users#my_data_maps'

    resources :data_maps 

    post 'tasks/retrieve_external_data'

    devise_for :users, :path => 'accounts'

end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def help
  end

  def faq
  end
end

app/helpers/info_helper.rb
module InfoHelper
end

app/views/info/faq.html.erb
<h1>Info#faq</h1>
<p>Find me in app/views/info/faq.html.erb</p>

app/views/info/help.html.erb
<h3><%= t :help %></h3>
<h4><%= t '.terms' %></h4>
<p>
<dl>
    <dt><%= DataMap.model_name.human %></dt>
    <dd><%= t '.data_map_def' %></dd>
    <dt><%= Field.model_name.human %></dt>
    <dd><%= t '.field_def' %></dd>
    <dt><%= PlaceField.model_name.human %><dt>
    <dd><%= t '.spot_def' %></dd>
    <dt><%= Place.model_name.human %></dt>
    <dd><%= t '.place_def' %></dd>
    <dt><%= ColorTheme.model_name.human %></dt>
    <dd><%= t '.color_theme_def' %></dd>
</p>

<h4><%= t '.process' %></h4>
<h5><%= t '.creating', :data_map => DataMap.model_name.human %></h5>
<p>
    <%= t '.creating_intro' %>
    <ol>
        <li>
        <p>
        <%= t '.req_column_intro', :req_column_count => Code::Application.config.place_column_names[:required].count.to_s %>
            <ul>
                <% Code::Application.config.place_column_names[:required].each do |internal_name, name| %>
                    <li>
                    <% case internal_name %>
                    <% when :name %>
                      <%= t '.name_column', :name => name %>
                    <% when :latitude %>
                      <%= t '.lat_column', :name => name %>
                    <% when :longitude %>
                      <%= t '.lon_column', :name => name %>
                    <% end %>
                    </li>
                <% end %>
            </ul>
            </p>
            <p>
            <%= t '.opt_column_intro' %>
            <ul>
                <li>
                <%= t '.api_abbr_column', :name => Code::Application.config.place_column_names[:optional][:api_abbr] %>
                </li>
            </ul>
            </p>
        </li>
        <li>
            <%= t '.fill_in_data' %>
        </li>
        <li>
            <%= t '.user_data' %>
        </li>
        <li>
            <%= t '.save_csv' %>
        </li>
        <li>
        <%= t '.create_account_html', :create_link => link_to(t('.create'), new_user_registration_path), :login_link => link_to(t('.login'), user_session_path) %>
        </li> 
        <li>
            <%= t '.create_data_map_html', :create_link => link_to(t('.create').downcase, new_data_map_path) %>
        </li>
    </ol>
</p>
<h5><%= t '.viewing', :data_map => DataMap.model_name.human %></h5>
<p>
    <%= t '.viewing_text' %> 
</p>