config/routes.rb
Code::Application.routes.draw do

    root :to => 'data_maps#index'

    match 'help' => 'info#help'
    match 'faq' => 'info#faq'
    match 'my_data_maps' => 'users#my_data_maps'

    resources :data_maps 

    post 'tasks/retrieve_external_data'

    devise_for :users, :path => 'accounts'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t :app_title %> - <%= if content_for?(:title) then yield :title else t :app_subtitle end %></title>
  <%= stylesheet_link_tag 'application', :media => 'all' %>
  <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Asap:400,700,400italic|Terminal+Dosis' %>
  <!--[if IE 6]><%# stylesheet_link_tag 'ie6' %><![endif]-->
  <!--[if IE 7]><%# stylesheet_link_tag 'ie7' %><![endif]-->
  <!--[if lt IE 9]><%= javascript_include_tag "//html5shiv.googlecode.com/svn/trunk/html5.js"%><![endif]-->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header role="banner">
        <hgroup>
            <h1 id="app-title"><%= t :app_title %></h1>
            <h2 id="app-subtitle"><%= t :app_subtitle %></h2>
        </hgroup>
        <nav role="navigation">
            <a id="skip-link" href="#content" title="<%= t '.skip_link' %>"><%= t '.skip_link' %></a>
            <ul id="menu">
                <li><%= link_to t('home'), root_path %></li>
                <% if user_signed_in? %>
                    <li><%= link_to t('account'), edit_user_registration_path %></li>
                    <li><%= link_to t('devise.sign_out'), destroy_user_session_path, :method => :delete %></li>
                <% else %>
                    <li><%= link_to t('devise.sign_in'), new_user_session_path %></li>
                <% end %>
                <li><%= link_to t('help'), help_path %></li> 
            </ul>
        </nav>
    </header>
    <div id="content" role="main">
        <% if flash[:notice] %>
            <p class="flash notice"><%= flash[:notice] %></p>
        <% end %>
        <% if flash[:alert] %>
            <p class="flash alert"><%= flash[:alert] %></p>
        <% end %>
        <% if flash[:error] %>
            <p class="flash error"><%= flash[:error] %></p>
        <% end %>
        <%= yield %>
    </div>
    <footer>
        <p id="copyright"><%= t '.footer_html'%></p>
    </footer>
</body>
</html>